/* 共通の端末内ランキング。競技・難易度を分け、同じ名前は最高記録を残す。 */
(()=>{'use strict';const KEY='kokko_arcade_boards_v1',memory=new Map();let persistent=true;
const games={cyberrunner:'CYBER RUNNER',generator:'発電機',cannon:'仕分け',battle:'カード整列',math:'暗算',merge:'マージタワー'};
function read(key,fallback){try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw);}catch{persistent=false;return memory.get(key)??fallback;}}
function write(key,value){memory.set(key,value);try{localStorage.setItem(key,JSON.stringify(value));}catch{persistent=false;}}
function name(value){return String(value||'GUEST').trim().replace(/[\u0000-\u001f\u007f]/g,'').slice(0,12)||'GUEST';}
function profile(){return name(read('kokko_arcade_profile_v1',{})?.name||read('cyberrunner_save_v1',{})?.playerName);}
function setProfile(value){const player=name(value);write('kokko_arcade_profile_v1',{name:player});const old=read('cyberrunner_save_v1',null);if(old&&typeof old==='object'&&!Array.isArray(old))write('cyberrunner_save_v1',{...old,playerName:player});return player;}
function clean(row){if(!row||!Number.isFinite(Number(row.score))||Number(row.score)<0||Number(row.score)>1e8)return null;return{...row,name:name(row.name),score:Math.floor(Number(row.score)),title:String(row.title||'挑戦者').slice(0,40),comp:Math.max(0,Math.min(100,Number(row.comp)||0))};}
function unique(rows){const result=new Map();for(const raw of rows){const r=clean(raw);if(!r)continue;const prior=result.get(r.name);if(!prior||r.score>prior.score||(r.score===prior.score&&r.comp>prior.comp))result.set(r.name,r);}return [...result.values()].sort((a,b)=>b.score-a.score||b.comp-a.comp).slice(0,10);}
function legacy(game,mode){const key=game==='cyberrunner'?'cyberrunner_ranks_v1':game==='generator'?'kokko_calibration_v4_'+mode:null;const data=key?read(key,[]):[];return Array.isArray(data)?data:[];}
function list(game,mode){const all=read(KEY,{}),stored=all?.[game+'|'+mode];return unique([...(Array.isArray(stored)?stored:[]),...legacy(game,mode)]);}
function save(game,mode,row){if(!games[game])return[];const all=read(KEY,{}),boards=all&&typeof all==='object'&&!Array.isArray(all)?all:{};const result=unique([...list(game,String(mode)),{...row,name:row.name||profile()}]);boards[game+'|'+mode]=result;write(KEY,boards);window.dispatchEvent(new CustomEvent('arcade-ranking-change'));return result;}
function modes(game){const defaults={cyberrunner:['standard'],generator:['easy','normal','expert'],cannon:['standard'],battle:['easy','normal','hard'],math:['time_easy','time_normal','time_hard','survival_normal','endless_normal'],merge:['stabilizer','overload']}[game]||['standard'];const boards=read(KEY,{});return [...new Set([...defaults,...Object.keys(boards||{}).filter(k=>k.startsWith(game+'|')).map(k=>k.split('|')[1])])];}
function label(mode){return({standard:'標準',easy:'やさしい',normal:'ふつう',hard:'難しい',expert:'むずかしい',stabilizer:'安定化',overload:'高負荷',time:'時間制',survival:'サバイバル',endless:'練習'})[mode]||mode.split('_').map(m=>({time:'時間制',survival:'生存',endless:'練習',easy:'やさしい',normal:'ふつう',hard:'難しい',insane:'超難度'})[m]||m).join(' / ');}
window.ArcadeHub=Object.freeze({games,list,save,profile,setProfile,modes,label,persistent:()=>persistent});
function install(){const style=document.createElement('style');style.textContent=`.arcade-board{width:min(680px,calc(100vw - 24px));max-height:calc(100dvh - 24px);border:1px solid #678c7b;border-radius:18px;background:#fffef8;color:#163a36;padding:22px;font:14px Meiryo,sans-serif;box-shadow:0 22px 80px #0006}.arcade-board::backdrop{background:#06121ccc;backdrop-filter:blur(5px)}.arcade-board h2{font-size:22px;margin:0}.ab-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.ab-head button,.ab-pager button{border:1px solid #9ab49f;background:#fffef8;color:#163a36;border-radius:8px;min-height:44px;padding:8px 13px;font:inherit;cursor:pointer}.ab-controls{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:18px 0 12px}.ab-controls label{font-size:11px}.ab-controls select{display:block;width:100%;height:44px;border:1px solid #9ab49f;background:white;color:#163a36;border-radius:8px;font:14px Meiryo;padding:5px}.ab-rows{list-style:none;padding:0;margin:0}.ab-row{display:grid;grid-template-columns:30px 1fr auto;gap:12px;align-items:center;border-bottom:1px solid #d4decf;padding:12px 0;min-height:58px}.ab-row>span:first-child{font:700 17px Consolas;color:#46775d}.ab-row:first-child>span:first-child{color:#9c6711}.ab-player{overflow-wrap:anywhere}.ab-player small{display:block;font-size:10px;color:#536e62}.ab-score{font:700 24px Consolas}.ab-empty{padding:38px 0;text-align:center;color:#536e62}.ab-pager{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:16px}.ab-note{font-size:10px;line-height:1.6;color:#536e62;margin:14px 0 0}.arcade-board button:focus-visible,.arcade-board select:focus-visible{outline:3px solid #b98628;outline-offset:3px}@media(max-width:600px){.arcade-board{padding:16px}.arcade-board h2{font-size:18px}.ab-controls{gap:8px;margin:12px 0 8px}.ab-row{min-height:52px;padding:9px 0}.ab-score{font-size:21px}.ab-note{margin-top:10px}}@media(max-height:500px){.arcade-board{padding:12px}.ab-row{min-height:38px;padding:5px 0}.ab-controls{margin:8px 0}.ab-controls select{height:36px}.ab-head button,.ab-pager button{min-height:36px}.ab-pager{margin-top:8px}.ab-note{margin-top:8px}}`;document.head.append(style);
const dialog=document.createElement('dialog');dialog.className='arcade-board';dialog.setAttribute('aria-label','全ゲームのランキング');dialog.innerHTML='<div class="ab-head"><h2>ARCADE ランキング</h2><button type="button" class="ab-close">閉じる ×</button></div><div class="ab-controls"><label>ゲーム<select class="ab-game"></select></label><label>難易度・モード<select class="ab-mode"></select></label></div><ol class="ab-rows"></ol><div class="ab-pager"><button class="ab-prev">← 前へ</button><span class="ab-page"></span><button class="ab-next">次へ →</button></div><p class="ab-note"></p>';document.body.append(dialog);
const gameSelect=dialog.querySelector('.ab-game'),modeSelect=dialog.querySelector('.ab-mode');for(const [id,title]of Object.entries(games)){const option=new Option(title,id);gameSelect.append(option);}let page=0,opener=null;
function options(){modeSelect.replaceChildren();for(const m of modes(gameSelect.value))modeSelect.append(new Option(label(m),m));page=0;render();}
function render(){const rows=list(gameSelect.value,modeSelect.value),size=innerHeight<480?2:innerHeight<720?3:5,pages=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,pages-1);const target=dialog.querySelector('.ab-rows');target.replaceChildren();if(!rows.length){const li=document.createElement('li');li.className='ab-empty';li.textContent='まだ記録なし。最初の挑戦者になろう。';target.append(li);}rows.slice(page*size,(page+1)*size).forEach((row,i)=>{const li=document.createElement('li');li.className='ab-row';const rank=document.createElement('span');rank.textContent=String(page*size+i+1).padStart(2,'0');const player=document.createElement('span');player.className='ab-player';player.textContent=row.name;const title=document.createElement('small');title.textContent=row.title;player.append(title);const score=document.createElement('b');score.className='ab-score';score.textContent=row.score.toLocaleString();li.append(rank,player,score);target.append(li);});dialog.querySelector('.ab-page').textContent=(page+1)+' / '+pages;dialog.querySelector('.ab-prev').disabled=page===0;dialog.querySelector('.ab-next').disabled=page===pages-1;dialog.querySelector('.ab-note').textContent=(persistent?'この端末の記録。':'保存が使えないため、この画面を閉じるまでの記録。')+' 同じ名前は最高記録だけ。ゲーム・難易度別に順位を表示します。';}
function open(game='generator',mode='normal'){opener=document.activeElement;gameSelect.value=games[game]?game:'generator';options();if([...modeSelect.options].some(o=>o.value===mode))modeSelect.value=mode;page=0;render();dialog.showModal();}
dialog.querySelector('.ab-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>opener?.focus?.({preventScroll:true}));gameSelect.onchange=options;modeSelect.onchange=()=>{page=0;render();};dialog.querySelector('.ab-prev').onclick=()=>{page--;render();};dialog.querySelector('.ab-next').onclick=()=>{page++;render();};window.addEventListener('resize',()=>{if(dialog.open)render();});window.addEventListener('arcade-ranking-change',()=>{if(dialog.open)render();});window.openArcadeRanking=open;
document.addEventListener('click',e=>{const button=e.target.closest('[data-arcade-rank]');if(button){e.preventDefault();open(button.dataset.arcadeRank||'generator',button.dataset.rankMode||'normal');}});
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
