/* オリジナルのシンセBGM / 効果音。外部音源・通信・追加ライブラリ不要。 */
(()=>{'use strict';
let ctx=null,master=null,enabled=false,music=false,timer=0,nextBeat=0,step=0;const voices=new Set();
function context(){if(!ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return null;ctx=new Audio();master=ctx.createGain();master.gain.value=.42;const limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-12;limiter.ratio.value=6;master.connect(limiter);limiter.connect(ctx.destination);}if(ctx.state==='suspended')ctx.resume().catch(()=>{});return ctx;}
function tone(hz,time,length=.14,volume=.07,type='sine',group='fx',endHz=hz){if(!enabled||!ctx||voices.size>=48)return;const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(hz,time);if(endHz!==hz)oscillator.frequency.exponentialRampToValueAtTime(Math.max(20,endHz),time+length);gain.gain.setValueAtTime(.0001,time);gain.gain.linearRampToValueAtTime(volume,time+.008);gain.gain.exponentialRampToValueAtTime(.0001,time+length);oscillator.connect(gain);gain.connect(master);const voice={oscillator,gain,group};voices.add(voice);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();voices.delete(voice);};oscillator.start(time);oscillator.stop(time+length+.02);}
function stopVoices(group){for(const voice of voices){if(group&&voice.group!==group)continue;try{voice.oscillator.stop();}catch{}}}
function stop(){music=false;clearInterval(timer);timer=0;stopVoices('music');}
function schedule(){if(!music||!enabled||!ctx)return;const now=ctx.currentTime;if(nextBeat<now-.3)nextBeat=now+.015;const notes=[220,261.63,329.63,293.66,220,261.63,392,329.63];while(nextBeat<now+.18){tone(notes[step%8],nextBeat,.12,.022,'triangle','music');if(step%4===0){tone(step%8===0?110:130.81,nextBeat,.33,.036,'sine','music');tone(95,nextBeat,.10,.036,'sine','music',38);}step++;nextBeat+=60/112/2;}}
function start(){if(!enabled||music)return;try{if(!context())return;music=true;step=0;nextBeat=ctx.currentTime+.025;schedule();timer=setInterval(schedule,80);}catch{stop();}}
function play(kind){if(!enabled)return;try{if(!context())return;const now=ctx.currentTime+.008;const sequence=(notes,gap=.06,volume=.075)=>notes.forEach((hz,i)=>tone(hz,now+i*gap,.13,volume,'sine'));if(kind==='perfect')sequence([659.25,987.77,1318.51]);else if(kind==='good')sequence([523.25,783.99]);else if(kind==='miss'){tone(190,now,.17,.065,'triangle','fx',75);tone(140,now+.05,.12,.045,'sine','fx',55);}else if(kind==='go')sequence([523.25,659.25,783.99],.045);else if(kind==='combo')sequence([523.25,659.25,783.99,1046.5],.055,.09);else if(kind==='record')sequence([523.25,659.25,783.99,1046.5,1318.5],.11,.075);else if(kind==='finish')sequence([783.99,659.25,523.25],.10);else tone(440,now,.08,.055);}catch{stop();}}
function setEnabled(value){enabled=!!value;if(!enabled){stop();if(master)master.gain.setTargetAtTime(0,ctx.currentTime,.008);stopVoices();}else if(context())master.gain.setTargetAtTime(.42,ctx.currentTime,.012);return enabled;}
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();stopVoices();}});window.addEventListener('pagehide',()=>{stop();stopVoices();if(ctx)ctx.suspend().catch(()=>{});});
window.ArcadeAudio=Object.freeze({setEnabled,start,stop,play});
})();
