(()=>{'use strict';
const $=id=>document.getElementById(id),R=window.ArcadeRanking;
const MODES={easy:{name:'やさしい',label:'EASY',width:88,speed:150,keys:['Space'],sequence:['Space'],detail:'SPACEひとつでOK。広い帯でタイミングに慣れよう。'},normal:{name:'ふつう',label:'NORMAL',width:54,speed:210,keys:['ArrowLeft','Space','ArrowRight'],sequence:['Space','ArrowLeft','ArrowRight','ArrowLeft','Space','ArrowRight'],detail:'指定キーが変わる。帯の中心を狙って倍率を守ろう。'},expert:{name:'むずかしい',label:'EXPERT',width:34,speed:270,keys:['ArrowLeft','Space','ArrowRight','ArrowUp'],sequence:['ArrowLeft','Space','ArrowUp','ArrowRight','ArrowUp','ArrowLeft','ArrowRight','Space'],detail:'4キー・高速回転・狭い帯。毎回キーを確認しよう。'}};
const CENTERS=[170,125,205,145,190,110,225,160,180,130,200,155],LABELS={Space:'SPACE',ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑'},HELP={Space:'スペース',ArrowLeft:'左キー',ArrowRight:'右キー',ArrowUp:'上キー'},DURATION=30000,pressed=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)');
let mode='normal',state='ready',phase='idle',frame=0,clockStart=0,countStart=0,phaseStart=0,activeStart=0,previousCount=0,angle=0,center=170,width=54,speed=150,required='Space',score=0,combo=0,maxCombo=0,hits=0,attempts=0,perfects=0,precisionTotal=0,best=0,roundName='GUEST',lastResult=null,finishAt=0,rankView='local',rankEpoch=0,sound=true,direction=1,anchorAngle=0,targetTravel=170,lockUntil=0,feedbackUntil=0;
const machine=$('machine'),action=$('action'),instrument=$('instrument'),particles=$('particles'),keypad=$('keypad');
try{sound=localStorage.getItem('kokko_sound_v3')!=='off';}catch{}$('sound').textContent='音 '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(sound));$('nickname').value=R.profile()==='GUEST'?'':R.profile();
function notify(title,sub,kind=''){$('feedback').className='feedback '+kind;$('feedback-title').textContent=title;$('feedback-sub').textContent=sub;}
function multi(){return 1+Math.min(4,Math.floor(combo/5))*.5;}
function drawScore(){$('score').textContent=score.toLocaleString();$('best-hint').textContent=best?score>best?'自己ベスト更新中！':`自己ベスト ${best.toLocaleString()}点 / あと${(best-score+1).toLocaleString()}点`:'最初の記録をつくろう';$('combo').textContent=combo;$('multiplier').textContent='×'+multi().toFixed(1);[...$('combo-meter').children].forEach((b,i)=>b.classList.toggle('on',i<(combo>=20?5:combo%5)));$('combo-hint').textContent=combo>=20?'倍率MAX。中心を狙って出力を伸ばそう。':`あと${5-combo%5}連続成功で ×${(multi()+.5).toFixed(1)}`;}
function point(deg,r=108){const a=(deg-90)*Math.PI/180;return[140+r*Math.cos(a),140+r*Math.sin(a)];}
function arc(from,to){const a=point(from),b=point(to);return`M ${a[0]} ${a[1]} A 108 108 0 ${to-from>180?1:0} 1 ${b[0]} ${b[1]}`;}
function drawDial(){ $('zone').setAttribute('d',arc(center-width/2,center+width/2));$('perfect-zone').setAttribute('d',arc(center-width*.1,center+width*.1));$('needle').style.transform=`rotate(${angle}deg)`;instrument.dataset.angle=angle.toFixed(3);instrument.dataset.center=center;instrument.dataset.width=width;instrument.dataset.required=required;instrument.dataset.phase=phase;instrument.dataset.direction=direction===1?'clockwise':'counterclockwise';}
function setPhase(value){phase=value;instrument.dataset.phase=value;}
function keyButtons(){keypad.replaceChildren();keypad.style.setProperty('--keys',MODES[mode].keys.length);for(const key of MODES[mode].keys){const button=document.createElement('button');button.type='button';button.dataset.key=key;button.setAttribute('aria-label',HELP[key]+'で調整');const label=document.createElement('span');label.textContent=LABELS[key];const help=document.createElement('small');help.textContent=HELP[key];button.append(label,help);button.addEventListener('click',()=>input(key));keypad.append(button);}}
function lockSettings(lock){$('nickname').disabled=lock;document.querySelectorAll('[data-mode]').forEach(b=>b.disabled=lock);}
function clearEffects(){for(const node of particles.children)node.getAnimations().forEach(a=>a.cancel());particles.replaceChildren();$('float-score').getAnimations().forEach(a=>a.cancel());$('float-score').textContent='';machine.classList.remove('flash-good','flash-miss');$('score').classList.remove('score-pop');}
function fx(kind,earned){if(reduced.matches)return;const cname=kind==='miss'?'flash-miss':'flash-good';machine.classList.remove('flash-good','flash-miss');requestAnimationFrame(()=>{if(state==='running')machine.classList.add(cname);});$('score').classList.remove('score-pop');requestAnimationFrame(()=>$('score').classList.add('score-pop'));const text=$('float-score');text.getAnimations().forEach(a=>a.cancel());text.textContent=earned>0?'+'+earned:'−50';text.style.color=kind==='miss'?'var(--red)':'var(--gold)';text.animate([{opacity:0,transform:'translate(-50%,10px)'},{opacity:1,offset:.2,transform:'translate(-50%,0)'},{opacity:0,transform:'translate(-50%,-26px)'}],{duration:640,fill:'forwards'});if(kind!=='miss'){const n=kind==='perfect'?14:8;for(let i=0;i<n&&particles.children.length<42;i++){const dot=document.createElement('i');dot.className='particle';const a=i/n*Math.PI*2;particles.append(dot);dot.animate([{opacity:1,transform:'translate(0,0) scale(1)'},{opacity:0,transform:`translate(${Math.cos(a)*112}px,${Math.sin(a)*112}px) scale(.3)`}],{duration:450+(i%3)*65,easing:'ease-out'}).onfinish=()=>dot.remove();}}}
function beep(kind){if(!sound)return;window.ArcadeAudio.setEnabled(true);window.ArcadeAudio.play(kind);}
function drawRanking(rows){const list=$('rank-list');list.replaceChildren();if(!rows.length){const item=document.createElement('li');item.className='empty-rank';item.textContent='まだ記録なし。最初の挑戦者になろう。';list.append(item);return;}rows.slice(0,10).forEach((row,i)=>{const item=document.createElement('li');item.className='rank-row';const place=document.createElement('span');place.className='rank-place';place.textContent=String(i+1).padStart(2,'0');const name=document.createElement('span');name.className='rank-player';name.textContent=R.cleanName(row.name);const title=document.createElement('small');title.textContent=String(row.title||'ルーキー').slice(0,40)+' / 精度 '+Math.round(Number(row.comp)||0)+'%';name.append(title);const value=document.createElement('b');value.className='rank-points';value.textContent=(Number(row.score)||0).toLocaleString();item.append(place,name,value);list.append(item);});}
async function refreshRanking(){const epoch=++rankEpoch;$('rank-mode').textContent=MODES[mode].name;$('tab-local').setAttribute('aria-pressed',String(rankView==='local'));$('tab-global').setAttribute('aria-pressed',String(rankView==='global'));if(rankView==='local'){drawRanking(R.list(mode));$('rank-status').textContent=R.persistent()?'名前・称号・スコアをこの端末に保存。':'保存が使えないため、記録は画面を閉じるまで。';return;}if(!R.sharedReady()){drawRanking([]);$('rank-status').textContent='共有は準備中。この筐体のランキングで遊べます。';return;}drawRanking([]);$('rank-status').textContent='共有ランキングを読み込み中…';try{const data=await R.fetch(mode);if(epoch!==rankEpoch)return;drawRanking(data);$('rank-status').textContent='同じゲーム・同じ難易度の共有TOP10。';}catch(e){if(epoch===rankEpoch)$('rank-status').textContent=e.message;}}
function ready(note=''){window.ArcadeAudio.stop();cancelAnimationFrame(frame);state='ready';machine.dataset.state=state;setPhase('idle');document.body.classList.remove('playing');machine.classList.remove('is-result','preview','urgent');$('result').classList.add('hidden');instrument.classList.remove('hidden');action.classList.remove('hidden');keypad.classList.add('hidden');action.disabled=false;action.textContent='30秒の挑戦を始める →';lockSettings(false);score=combo=maxCombo=hits=attempts=perfects=precisionTotal=0;angle=0;direction=1;anchorAngle=0;targetTravel=CENTERS[0];center=CENTERS[0];width=MODES[mode].width;required=MODES[mode].sequence[0];best=R.personal(mode,$('nickname').value||R.profile());$('required-key').textContent=LABELS[required];$('key-label').textContent='次に押すキー';$('dial-hint').textContent='時計回り ↻';$('level-label').textContent=MODES[mode].label;$('status').textContent='STANDBY';$('check-no').textContent='01';$('time').textContent='30.0';$('time-fill').style.transform='scaleX(1)';$('mode-detail').textContent=MODES[mode].detail;$('session-note').textContent='押すたびに方向切替。長押し・連打は無効。';$('control-hint').textContent='キーボードでも、画面のキーをタップしても遊べます。';drawScore();drawDial();clearEffects();keyButtons();notify('光る帯で、指定キーを押す。',note||'針が緑の帯に重なる瞬間を狙おう。');refreshRanking();}
function begin(){if(state!=='ready'&&state!=='result')return;roundName=R.setProfile($('nickname').value);ready();state='countdown';machine.dataset.state=state;lockSettings(true);document.body.classList.add('playing');action.disabled=true;action.textContent='準備してね';countStart=performance.now();previousCount=3;$('status').textContent='READY';notify('3','キーを確認。針が動いたら帯を狙おう。');if(innerWidth<=740||innerHeight<=900)machine.scrollIntoView({block:'start'});beep('ready');frame=requestAnimationFrame(tick);}
function newCheck(now,keepFeedback=false){
 setPhase('active');phaseStart=activeStart=now;anchorAngle=angle;targetTravel=CENTERS[attempts%CENTERS.length];
 center=(anchorAngle+direction*targetTravel+720)%360;required=MODES[mode].sequence[attempts%MODES[mode].sequence.length];
 width=MODES[mode].width*Math.max(.8,1-hits*.008);speed=MODES[mode].speed*(1+Math.min(.45,hits*.025));
 lockUntil=now+(attempts===0?0:120);machine.classList.remove('preview');$('required-key').textContent=LABELS[required];
 $('check-no').textContent=String(attempts+1).padStart(2,'0');$('dial-hint').textContent=direction===1?'時計回り ↻':'反時計回り ↺';
 $('status').textContent=direction===1?'CLOCKWISE ↻':'REVERSE ↺';
 [...keypad.children].forEach(b=>{b.disabled=now<lockUntil;b.classList.remove('used');});
 if(!keepFeedback)notify('緑の帯で、指定キーを押す。',LABELS[required]+' / 押すたびに回転方向が切り替わる');drawDial();
}
function run(now){if(sound){window.ArcadeAudio.setEnabled(true);window.ArcadeAudio.start();beep('go');}state='running';machine.dataset.state=state;clockStart=now;action.classList.add('hidden');keypad.classList.remove('hidden');$('control-hint').textContent='指定と違うキーはMISS。長押しでは調整できません。';$('session-note').textContent='入力直後に逆回転。テンポよく次の帯を狙おう。';newCheck(now);}
function resolve(ok,reason,now,clicked=false){
 if(phase!=='active')return;const error=Math.abs(((angle-center+540)%360)-180),accuracy=Math.max(0,1-error/(width/2));
 attempts++;if(clicked)direction*=-1;
 if(ok){hits++;combo++;maxCombo=Math.max(maxCombo,combo);precisionTotal+=accuracy;const perfect=accuracy>=.8;if(perfect)perfects++;
  const base=perfect?100:Math.min(99,Math.round(60+accuracy*50)),earned=Math.round(base*multi());score+=earned;
  notify(perfect?'PERFECT!':'GOOD!',`+${earned}点 / ${combo} COMBO / 次は${direction===1?'時計回り':'反時計回り'}`,perfect?'perfect':'good');
  fx(perfect?'perfect':'good',earned);beep(combo%5===0?'combo':perfect?'perfect':'good');
 }else{score=Math.max(0,score-50);combo=0;notify('MISS',reason+' / −50点・コンボリセット','miss');fx('miss',-50);beep('miss');}
 feedbackUntil=now+650;drawScore();newCheck(now,true);
}
function updateTime(now){const left=Math.max(0,DURATION-(now-clockStart));$('time').textContent=(left/1000).toFixed(1);$('time-fill').style.transform=`scaleX(${left/DURATION})`;machine.classList.toggle('urgent',left<=5000);return left;}
function updateActive(now){
 const travel=Math.max(0,(now-activeStart)/1000*speed);angle=(anchorAngle+direction*travel+720)%360;
 $('needle').style.transform=`rotate(${angle}deg)`;instrument.dataset.angle=angle.toFixed(3);
 if(travel>targetTravel+width/2+25)resolve(false,'押し忘れ',now,false);
}
function tick(now){
 if(state==='countdown'){const count=3-Math.floor((now-countStart)/1000);if(count<=0)run(now);else if(count!==previousCount){previousCount=count;notify(String(count),'キーを確認。押すたびに針が逆回転する。');beep('ready');}}
 else if(state==='running'){if(updateTime(now)<=0){finish();return;}if(phase==='active'){
  updateActive(now);[...keypad.children].forEach(b=>b.disabled=now<lockUntil);
  if(now>feedbackUntil){notify('帯に重なった瞬間に押す。','押すキー：'+LABELS[required]+' / '+(direction===1?'時計回り ↻':'反時計回り ↺'));feedbackUntil=Infinity;}
 }}if(state==='running'||state==='countdown')frame=requestAnimationFrame(tick);
}
function input(key){
 if(state!=='running'||phase!=='active')return;const now=performance.now();if(updateTime(now)<=0){finish();return;}
 if(now<lockUntil)return;updateActive(now);if(now<lockUntil)return;
 keypad.querySelector(`[data-key="${key}"]`)?.classList.add('used');
 if(key!==required){resolve(false,'指定キーと違います',now,true);return;}
 const error=Math.abs(((angle-center+540)%360)-180);resolve(error<=width/2,'帯の外で押しました',now,true);
}
function finish(){if(state!=='running')return;window.ArcadeAudio.stop();beep(score>best?'record':'finish');cancelAnimationFrame(frame);state='result';setPhase('finished');machine.dataset.state=state;finishAt=performance.now();document.body.classList.remove('playing');machine.classList.remove('preview');machine.classList.add('is-result');lockSettings(false);action.classList.remove('hidden');keypad.classList.add('hidden');action.disabled=false;action.textContent='もう一度、記録を超える →';$('result').classList.remove('hidden');$('time').textContent='0.0';$('time-fill').style.transform='scaleX(0)';const precision=hits?Math.round(precisionTotal/hits*100):0,title=score>=3600?'伝説のエンジニア':score>=2400?'キャリブレーションマスター':score>=1200?'精密エンジニア':score>=600?'調整のエース':'ルーキー';lastResult={mode,row:{name:roundName,score,title,comp:precision,combo:maxCombo,hits,attempts,perfects}};R.add(mode,lastResult.row);notify(score>best?'自己ベスト更新！':'30秒、調整完了。',`${roundName} / ${MODES[mode].name} / ${score.toLocaleString()}点`,score>best?'perfect':'');$('result-title').textContent=title;$('result-hits').textContent=hits+' / '+attempts;$('result-combo').textContent=maxCombo;$('result-precision').textContent=precision+'%';$('result-tip').textContent=maxCombo<5?'次の目標は5連続成功。まずは指定キーの確認から。':precision<70?'次は帯の中心を狙おう。PERFECTを増やすとさらに伸びる。':`中心を捉えたPERFECTは${perfects}回。次は最大コンボ${maxCombo+1}を目指そう。`;$('submit-score').classList.toggle('hidden',!R.sharedReady());$('submit-score').disabled=false;$('submit-status').textContent=R.sharedReady()?'送信するとニックネーム・スコア・称号を共有します。':'記録はこの筐体に保存。みんなランキングは準備中。';$('status').textContent='COMPLETE';$('control-hint').textContent='スペースキー、またはボタンで再挑戦。';$('session-note').textContent='難易度ごとにTOP10。次の人も同じ条件で挑戦できます。';refreshRanking();clearEffects();action.focus({preventScroll:true});}
action.addEventListener('click',()=>{if(state==='result'&&performance.now()-finishAt<500)return;begin();});$('reset').addEventListener('click',()=>ready('前の挑戦は記録せず、新しく始められます。'));
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{if(state==='running'||state==='countdown')return;mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));lastResult=null;ready();}));
$('nickname').addEventListener('change',()=>{R.setProfile($('nickname').value);best=R.personal(mode,$('nickname').value);drawScore();});$('tab-local').addEventListener('click',()=>{rankView='local';refreshRanking();});$('tab-global').addEventListener('click',()=>{rankView='global';refreshRanking();});
$('submit-score').addEventListener('click',async()=>{if(!lastResult||$('submit-score').disabled)return;const result=lastResult;const button=$('submit-score');button.disabled=true;$('submit-status').textContent='送信中…';try{await R.submit(result.mode,result.row);if(lastResult!==result||state!=='result')return;$('submit-status').textContent='共有ランキングに送信しました。';rankView='global';refreshRanking();}catch(e){if(lastResult===result&&state==='result'){$('submit-status').textContent=e.message;button.disabled=false;}}});
$('sound').addEventListener('click',()=>{sound=!sound;$('sound').textContent='音 '+(sound?'ON':'OFF');$('sound').setAttribute('aria-pressed',String(sound));try{localStorage.setItem('kokko_sound_v3',sound?'on':'off');}catch{}window.ArcadeAudio.setEnabled(sound);if(sound){beep('good');if(state==='running')window.ArcadeAudio.start();}});
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.ctrlKey||e.altKey||e.metaKey||e.isComposing)return;if(e.target instanceof HTMLInputElement)return;if(!['Space','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))return;if(state==='running'||state==='countdown'){e.preventDefault();if(e.repeat||pressed.has(e.code))return;pressed.add(e.code);if(state==='running')input(e.code);return;}if(e.code==='Space'&&(e.target===document.body||e.target===action)){e.preventDefault();if(!e.repeat&&!pressed.has(e.code)){pressed.add(e.code);if(state!=='result'||performance.now()-finishAt>=500)begin();}}});document.addEventListener('keyup',e=>pressed.delete(e.code));window.addEventListener('blur',()=>pressed.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state==='running'||state==='countdown')){pressed.clear();ready('画面が切り替わったため中断しました。記録は登録しません。');}});ready();
})();
