/* 名前・称号・TOP10の形式をCYBER RUNNERに合わせ、異なる競技の点数は混ぜない。 */
(()=>{'use strict';
const prefix='kokko_calibration_v4_',memory=new Map();let persistent=true;
function read(key,fallback){try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw);}catch{persistent=false;return memory.has(key)?memory.get(key):fallback;}}
function write(key,value){memory.set(key,value);try{localStorage.setItem(key,JSON.stringify(value));}catch{persistent=false;}}
function cleanName(value){return String(value||'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,12)||'GUEST';}
function list(mode){const rows=read(prefix+mode,[]);if(!Array.isArray(rows))return[];return rows.filter(r=>r&&Number.isInteger(r.score)&&r.score>=0&&r.score<=50000&&typeof r.name==='string').map(r=>({...r,name:cleanName(r.name),title:String(r.title||'ルーキー').slice(0,40),comp:Math.max(0,Math.min(100,Number(r.comp)||0)),combo:Math.max(0,Math.min(100,Number(r.combo)||0))})).sort((a,b)=>b.score-a.score||b.comp-a.comp).slice(0,10);}
function personal(mode,name){name=cleanName(name);const value=read(prefix+'personal_'+mode+'_'+encodeURIComponent(name),0);if(Number.isInteger(value)&&value>0&&value<=50000)return value;return Math.max(0,...list(mode).filter(r=>r.name===name).map(r=>r.score));}
function add(mode,row){const name=cleanName(row.name),previous=personal(mode,name),result=[...list(mode),{...row,name}].sort((a,b)=>b.score-a.score||b.comp-a.comp).slice(0,10);write(prefix+mode,result);window.ArcadeHub?.save('generator',mode,row);if(row.score>previous)write(prefix+'personal_'+mode+'_'+encodeURIComponent(name),row.score);return result;}
function profile(){const legacy=read('cyberrunner_save_v1',{}),saved=read('kokko_arcade_profile_v1',{});return cleanName(saved?.name||legacy?.playerName);}
function setProfile(name){name=cleanName(name);write('kokko_arcade_profile_v1',{name});const legacy=read('cyberrunner_save_v1',null);if(legacy&&typeof legacy==='object'&&!Array.isArray(legacy))write('cyberrunner_save_v1',{...legacy,playerName:name});return name;}
function sharedReady(){const cfg=window.ARCADE_CONFIG?.sharedRanking;return !!(cfg?.enabled&&cfg.calibrationReady&&/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec$/.test(cfg.endpoint));}
async function request(mode,row){if(!sharedReady())throw Error('共有ランキングは未設定です。端末内の記録で遊べます。');const cfg=window.ARCADE_CONFIG.sharedRanking,controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const url=new URL(cfg.endpoint);url.searchParams.set('game','calibration');url.searchParams.set('mode',mode);const response=await fetch(url,row?{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...row,game:'calibration',mode}),signal:controller.signal}:{signal:controller.signal});if(!response.ok)throw Error('通信に失敗しました。端末の記録は保存されています。');const data=await response.json();if(!data.ok||data.game!=='calibration'||data.mode!==mode||!Array.isArray(data.ranking))throw Error('共有APIの更新が必要です。端末の記録は保存されています。');return data.ranking.slice(0,10);}catch(e){if(e.name==='AbortError')throw Error('通信が時間切れになりました。端末の記録は保存されています。');throw e;}finally{clearTimeout(timeout);}}
window.ArcadeRanking=Object.freeze({list,add,personal,profile,setProfile,cleanName,sharedReady,fetch:mode=>request(mode),submit:(mode,row)=>request(mode,row),persistent:()=>persistent});
})();
